import React from 'react';
import ReactDOM from 'react-dom';
import './index.css';
import App from './App';
import registerServiceWorker from './registerServiceWorker';
import {logSwitch} from './config/config';
import 'whatwg-fetch';
import 'es6-promise';
import {get,post} from './config/fetchAPI';
logSwitch();
ReactDOM.render(<App />, document.getElementById('root'));
registerServiceWorker();
